gravitee-io/gravitee-portal-webui

angular.json
package-lock.json
package.json
src/app/app.component.html

Closes gravitee-io/issues#2747

chore: add tachyons dependency

---

angular.json
src/app/app-routing.module.ts
src/app/app.component.html
src/app/app.component.spec.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/mock.helper.spec.ts
src/app/pages/apps/apps.component.html
src/app/pages/apps/apps.component.spec.ts
src/app/pages/apps/apps.component.ts
src/app/pages/catalog/catalog.component.html
src/app/pages/catalog/catalog.component.spec.ts
src/app/pages/catalog/catalog.component.ts
src/app/pages/dashboard/dashboard.component.html
src/app/pages/dashboard/dashboard.component.spec.ts
src/app/pages/dashboard/dashboard.component.ts
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/styles.scss

Closes gravitee-io/issues#2758

feat: add header

---

README.adoc
package-lock.json
package.json
src/app/app.component.ts
src/styles.scss

Closes gravitee-io/issues#2764

chore: upgrade gravitee-ui-components dependency

---

src/assets/i18n/cs.json

Relates to gravitee-io/issues#1853

Added Czech I18N

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/pages/catalog/all/all.component.css
src/app/pages/catalog/all/all.component.html
src/app/pages/catalog/all/all.component.spec.ts
src/app/pages/catalog/all/all.component.ts
src/app/pages/catalog/catalog.component.html
src/app/pages/catalog/categories/categories.component.css
src/app/pages/catalog/categories/categories.component.html
src/app/pages/catalog/categories/categories.component.spec.ts
src/app/pages/catalog/categories/categories.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

Closes gravitee-io/issues#2788

feat(portal): allow a user to display the list of categories

---

src/app/pages/catalog/categories/categories.component.ts
src/app/pages/login/login.component.ts
src/app/pages/registration/registration-confirmation/registration-confirmation.component.ts
src/app/pages/registration/registration.component.ts

Closes gravitee-io/issues#2892

Use client sdk with single request parameter

---

src/app/app.component.spec.ts
src/app/app.component.ts
src/app/interceptors/apiRequest.interceptor.ts
src/app/layouts/layout/layout.component.html
src/app/pages/login/login.component.spec.ts
src/app/pages/login/login.component.ts
src/app/pages/user/user.component.html
src/app/pages/user/user.component.ts
src/app/services/current-user.service.ts

fix: Logged user is not well handled

---

README.adoc

doc: improve dev documentation

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/pages/contact/contact.component.css
src/app/pages/contact/contact.component.html
src/app/pages/contact/contact.component.spec.ts
src/app/pages/contact/contact.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

feat: Allow a user to contact owner of the platform

---

package.json
src/app/app-routing.module.ts
src/app/components/user-avatar/user-avatar.component.html
src/app/layouts/layout/layout.component.spec.ts
src/app/pages/catalog/catalog.component.ts
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.html
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts
src/app/pages/catalog/search/catalog-search.component.css
src/app/pages/catalog/search/catalog-search.component.html
src/app/pages/catalog/search/catalog-search.component.ts
src/app/pages/contact/contact.component.spec.ts
src/app/services/route.service.spec.ts
src/app/services/route.service.ts

fix gravitee-io/issues#2939
fix gravitee-io/issues#2942

fix: add states, labels and rating to cards

---

src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts
src/app/pages/catalog/search/catalog-search.component.css
src/app/pages/catalog/search/catalog-search.component.html
src/app/pages/catalog/search/catalog-search.component.ts
src/app/pages/contact/contact.component.css
src/app/pages/contact/contact.component.html
src/app/utils/search-query-param.enum.ts
src/styles.scss

refactor(search-catalog): use gv-pagination component

---

package.json
pom.xml
src/app/app-routing.module.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/interceptors/apiRequest.interceptor.ts
src/app/layouts/layout/layout.component.html
src/app/layouts/layout/layout.component.ts
src/app/model/notification.ts
src/app/pages/contact/contact.component.html
src/app/pages/contact/contact.component.ts
src/app/pages/login/login.component.html
src/app/pages/login/login.component.ts
src/app/pages/registration/registration-confirmation/registration-confirmation.component.html
src/app/pages/registration/registration-confirmation/registration-confirmation.component.ts
src/app/pages/registration/registration.component.html
src/app/pages/registration/registration.component.ts
src/app/pages/user/user.component.html
src/app/services/notification.service.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/environments/environment.ts
src/server-errors.ts

Closes gravitee-io/issues#2934

chore: Global handling of errors and notifications

---

src/app/app.component.ts
src/app/app.module.ts
src/app/interceptors/apiRequest.interceptor.ts
src/app/pages/catalog/search/catalog-search.component.html
src/app/pages/catalog/search/catalog-search.component.ts
src/app/pages/contact/contact.component.html
src/app/pages/contact/contact.component.ts
src/app/pages/login/login.component.html
src/app/services/loader.service.ts
src/app/services/notification.service.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

Closes gravitee-io/issues#2935

feat: Display a global loader when calling server

---

package.json
src/app/app-routing.module.ts
src/app/app.config.ts
src/app/app.module.ts
src/app/interceptors/api-request.interceptor.ts
src/app/layouts/layout/layout.component.spec.ts
src/app/layouts/layout/layout.component.ts
src/app/model/feature.ts
src/app/pages/catalog/catalog.component.spec.ts
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.html
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts
src/app/pages/contact/contact.component.html
src/app/pages/contact/contact.component.ts
src/app/pages/login/login.component.spec.ts
src/app/pages/login/login.component.ts
src/app/services/current-user.service.spec.ts
src/app/services/feature-guard.service.ts
src/app/services/route.service.spec.ts
src/app/services/route.service.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

feat: Add a feature flipping management

---

src/app/app-routing.module.ts
src/app/model/feature.ts
src/app/services/route.service.ts

Closes gravitee-io/issues#2882

feat: hide categories link in the menu when "enable view mode" is false

---

src/app/interceptors/api-request.interceptor.ts
src/app/layouts/layout/layout.component.ts
src/app/model/notification.ts
src/app/services/notification.service.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/server-errors.ts

Closes gravitee-io/issues#2961

feat: Display a fallback message when error code not defined

---

src/app/app.module.ts
src/app/pages/catalog/categories/categories.component.html
src/app/pages/catalog/categories/categories.component.ts
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.css
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.html
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.spec.ts
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts
src/app/pages/catalog/search/catalog-search.component.html
src/app/pages/catalog/search/catalog-search.component.spec.ts
src/app/pages/catalog/search/catalog-search.component.ts
src/app/pipes/api-labels.pipe.ts
src/app/pipes/api-states.pipe.ts
src/app/services/route.service.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/index.html
src/styles.scss

feat: add pagination & category filter to catalog

---

src/app/app.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/i18n-components.ts
src/i18n-server-errors.ts

Closes gravitee-io/issues#2940

feat: add i18n system

---

src/app/pages/catalog/categories/categories.component.ts
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts

Closes gravitee-io/issues#2965

chore(portal): pagination metadata are now numbers

---

src/app/app.component.ts
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.html
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts
src/app/pages/catalog/search/catalog-search.component.html
src/app/pages/catalog/search/catalog-search.component.ts
src/app/pages/login/login.component.ts
src/app/services/route.service.ts
src/assets/config.json
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/i18n-components.ts
src/styles.scss

Closes gravitee-io/issues#2955

feat: Handle empty states

---

src/app/layouts/layout/layout.component.html
src/app/pages/login/login.component.html

Closes gravitee-io/issues#2972

feat: Autofocus on login username

---

src/app/interceptors/api-request.interceptor.ts

fix: Cookie is not settled with a remote API endpoint

---

src/app/pages/catalog/filtered-catalog/filtered-catalog.component.html
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

Closes gravitee-io/issues#2960

feat(portal): use new resources for api metrics

---

src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts
src/app/pages/contact/contact.component.ts

Closes gravitee-io/issues#2791

feat: Allow a user to contact API owner

---

src/app/layouts/layout/layout.component.css
src/styles.scss

Closes gravitee-io/issues#2985

chore: Adapt height of content

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/components/gv-menu-header/gv-menu-header.component.html
src/app/components/gv-menu-header/gv-menu-header.component.spec.ts
src/app/components/gv-menu-header/gv-menu-header.component.ts
src/app/components/gv-search/gv-search.component.html
src/app/components/gv-search/gv-search.component.spec.ts
src/app/components/gv-search/gv-search.component.ts
src/app/directives/gv-menu-right-slot.directive.ts
src/app/directives/gv-menu-top-slot.directive.ts
src/app/layouts/layout/layout.component.html
src/app/layouts/layout/layout.component.ts

refactor(menu): use dynamic component injection from routing config

---

src/app/layouts/layout/layout.component.ts

fix(layout): clear viewContainerRef if route doesn't have slot

---

src/app/app.component.ts
src/app/app.module.ts
src/app/components/gv-menu-header/gv-menu-header.component.ts
src/app/layouts/layout/layout.component.ts
src/app/pages/login/login.component.spec.ts
src/app/pages/login/login.component.ts
src/app/services/auth-guard.service.spec.ts
src/app/services/auth-guard.service.ts
src/app/services/current-user.service.spec.ts
src/app/services/current-user.service.ts
src/app/services/nav-route.service.ts

fix(guard): return UrlTree for redirect if user is not authorized

---

src/app/layouts/layout/layout.component.css

Closes gravitee-io/issues#3037

fix: Fix user menu

---

src/app/layouts/layout/layout.component.css
src/app/layouts/layout/layout.component.ts

Closes gravitee-io/issues#2954

refactor: rename gv-nav-link to gv-link

---

src/app/layouts/layout/layout.component.ts

fix(nav): resolve navigation state

---

package-lock.json
src/app/services/auth.service.ts

fix(login): update user after loading instead of full reload

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/components/gv-documentation/gv-documentation.component.css
src/app/components/gv-documentation/gv-documentation.component.ts
src/app/components/gv-page-markdown/gv-page-markdown.component.css
src/app/components/gv-page-swaggerui/gv-page-swaggerui.component.css
src/app/components/gv-page/gv-page.component.css
src/app/layouts/layout/layout.component.css
src/app/layouts/layout/layout.component.html
src/app/layouts/layout/layout.component.ts
src/app/pages/api/api-contact/api-contact.component.css
src/app/pages/api/api-general/api-general.component.css
src/app/pages/api/api-general/api-general.component.ts
src/app/pages/applications/applications.component.spec.ts
src/app/pages/documentation/documentation.component.ts
src/app/pages/single-page/single-page.component.html
src/app/pages/single-page/single-page.component.spec.ts
src/app/pages/single-page/single-page.component.ts
src/app/services/nav-route.service.ts

Closes gravitee-io/issues#3048

feat(portal): header & footer links are now retrieved from portal API

---

src/app/components/gv-documentation/gv-documentation.component.ts
src/app/layouts/layout/layout.component.ts
src/assets/i18n/en.json

Closes gravitee-io/issues#3071

feat(portal): fix 'en' translation and fix documentation sorting

---

src/app/pipes/api-labels.pipe.ts

Closes gravitee-io/issues#3116

fix: Display labels on API cards

---

angular.json
package-lock.json
package.json
src/app/layouts/layout/layout.component.css
src/app/layouts/layout/layout.component.html
src/app/services/translation.service.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/styles.scss

Closes gravitee-io/issues#3036

chore: remove useless "tachyons" library

---

src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts

Closes gravitee-io/issues#3110

feat: Keep API display preference to the user

---

src/app/pages/login/login.component.html
src/app/pages/registration/registration-confirmation/registration-confirmation.component.html
src/app/pages/registration/registration.component.css
src/app/pages/registration/registration.component.html
src/styles.scss

feat(form): map autocomplete input attribute

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.html
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts

fix: set the scroll top to 0 at each page change except with an anchor

---

package-lock.json
package.json
src/app/layouts/layout/layout.component.html
src/app/layouts/layout/layout.component.ts
src/app/pages/account/account.component.css
src/app/pages/account/account.component.html
src/app/pages/account/account.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

Closes gravitee-io/issues#2806

feat: Allow a user to subscribe to notifications

---

src/app/pages/account/account.component.ts
src/app/services/current-user.service.ts

fix: Avatar is lost after navigation

---

src/assets/config.json
src/proxy.conf.json

Closes gravitee-io/issues#3182

feat(multi-env): add organization feature

---

src/app/app.component.ts
src/app/model/feature.enum.ts

Closes gravitee-io/issues#3344

feat(portal): add Google Analytics on portal

---

src/app/pages/login/login.component.html

fix(portal): add "type=submit" to login button

---

package.json
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/pages/login/login.component.html
src/app/pages/registration/registration-confirmation/registration-confirmation.component.html
src/app/pages/registration/registration.component.html
src/app/pages/reset-password/reset-password-confirmation/reset-password-confirmation.component.css
src/app/pages/reset-password/reset-password-confirmation/reset-password-confirmation.component.html
src/app/pages/reset-password/reset-password-confirmation/reset-password-confirmation.component.spec.ts
src/app/pages/reset-password/reset-password-confirmation/reset-password-confirmation.component.ts
src/app/pages/reset-password/reset-password.component.css
src/app/pages/reset-password/reset-password.component.html
src/app/pages/reset-password/reset-password.component.spec.ts
src/app/pages/reset-password/reset-password.component.ts
src/app/services/token.service.spec.ts
src/app/services/token.service.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/css/form.css

Closes gravitee-io/issues#2822

feat(portal): allow a user to reset his password

---

package-lock.json
package.json
src/app/services/nav-route.service.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

Closes gravitee-io/issues#3109

feat(portal) : add management link in portal usermenu

---

package-lock.json
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/pages/account/account.component.html
src/app/pages/application/application-notifications/application-notifications.component.css
src/app/pages/application/application-notifications/application-notifications.component.html
src/app/pages/application/application-notifications/application-notifications.component.spec.ts
src/app/pages/application/application-notifications/application-notifications.component.ts
src/app/services/analytics.service.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/i18n-dynamic-values.ts
src/i18n-server-errors.ts

Closes gravitee-io/issues#3115

feat: Allow a user to subscribe to notifications on an application

---

package-lock.json
package.json
src/app/app.component.html
src/app/app.module.ts
src/app/pages/account/account.component.css
src/app/pages/account/account.component.html
src/app/pages/account/account.component.ts

Closes gravitee-io/issues#2853

feat(portal): generate default picture for apis, applications and users

---

package-lock.json
package.json
src/app/app-routing.module.ts
src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts
src/app/pages/application/application-subscriptions/application-subscriptions.component.css
src/app/pages/application/application-subscriptions/application-subscriptions.component.html
src/app/pages/application/application-subscriptions/application-subscriptions.component.spec.ts
src/app/pages/application/application-subscriptions/application-subscriptions.component.ts
src/app/pages/subscriptions/subscriptions.component.html
src/app/pages/subscriptions/subscriptions.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/i18n-dynamic-values.ts

Closes gravitee-io/issues#3114

feat: Allow a user to consult subscriptions of an application

---

package.json
src/app/app-routing.module.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/components/gv-analytics-dashboard/gv-analytics-dashboard.component.ts
src/app/components/gv-analytics-filters/gv-analytics-filters.component.spec.ts
src/app/pages/application/application-general/application-general.component.html
src/app/pages/application/application-general/application-general.component.ts
src/app/pages/application/application-logs/application-logs.component.ts
src/app/pages/application/application-members/application-members.component.css
src/app/pages/application/application-members/application-members.component.html
src/app/pages/application/application-members/application-members.component.spec.ts
src/app/pages/application/application-members/application-members.component.ts
src/app/pages/application/application-subscriptions/application-subscriptions.component.ts
src/app/pages/registration/registration-confirmation/registration-confirmation.component.spec.ts
src/app/pages/registration/registration.component.spec.ts
src/app/pages/subscriptions/subscriptions.component.html
src/app/pages/subscriptions/subscriptions.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/i18n-components.ts

Closes gravitee-io/issues#2803

feat(portal): manage application members

---

src/app/app-routing.module.ts
src/app/components/gv-header-item/gv-header-item.component.ts
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.html
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts

Closes gravitee-io/issues#3178

feat(portal): display Views picture

---

src/app/pages/api/api-general/api-general.component.ts
src/app/pages/api/api-subscribe/api-subscribe.component.ts
src/app/pages/application/application-general/application-general.component.ts
src/app/pages/application/application-members/application-members.component.ts

Closes gravitee-io/issues#3436

feat(portal): use api version to generate default picture

---

src/app/app.component.css
src/app/app.component.html
src/app/app.component.ts
src/app/directives/gv-slot.ts
src/styles.scss

feat: display a sticky menu on scroll

---

src/app/components/gv-documentation/gv-documentation.component.css
src/app/components/gv-documentation/gv-documentation.component.ts
src/app/components/gv-page/gv-page.component.ts
src/app/pages/documentation/documentation.component.ts

fix: remove recursion when pages are already load

---

src/app/app-routing.module.ts

Closes gravitee-io/issues#3206

feat(multi-env): mix membership scopes MANAGEMENT & PORTAL

---

src/app/pages/registration/registration.component.html
src/app/pages/registration/registration.component.ts

feat: Allow users to subscribe to newsletters

---

src/assets/i18n/en.json

fix: Application: bad label on empty

---

src/app/app-routing.module.ts

fix: Slide effect not working on app members

---

src/app/app-routing.module.ts
src/app/app.component.ts
src/app/components/gv-header-item/gv-header-item.component.ts
src/app/pages/api/api-general/api-general.component.ts
src/app/pages/api/api-subscribe/api-subscribe.component.ts
src/app/resolvers/api.resolver.ts
src/app/services/nav-route.service.ts

fix: Avoid multiple calls on API/App page

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/pages/applications/applications-routing.module.ts
src/app/pages/applications/applications.module.ts
src/app/services/nav-route.service.ts
src/app/shared/shared.module.ts

chore: move /applications to lazy loading module

---

src/app/pages/application/application-general/application-general.component.css
src/app/pages/application/application-general/application-general.component.html

fix(portal): replace reset button by a link

---

src/app/app.module.ts
src/app/pages/applications/applications.module.ts
src/app/pages/user/user-notification/user-notification.component.ts
src/app/shared/shared.module.ts

fix: resolve applications module

---

src/app/pages/catalog/filtered-catalog/filtered-catalog.component.css
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts

fix: resolve skeleton mode on catalog

---

src/app/pages/applications/applications-routing.module.ts
src/app/pages/applications/applications.module.ts
src/app/pages/cookies/cookies.component.html
src/app/pages/cookies/cookies.component.spec.ts
src/app/pages/login/login.component.html
src/app/pages/login/login.component.ts
src/app/shared/shared.module.ts

fix: allow user to save credentials

---

src/app/pages/application/application-subscriptions/application-subscriptions.component.html
src/app/pages/application/application-subscriptions/application-subscriptions.component.ts

fix: JS error when refreshing the subscription's page

---

src/assets/i18n/fr.json

fix: i18n FR notification empty

---

src/app/components/gv-analytics-dashboard/gv-analytics-dashboard.component.ts

fix: Percent is incorrect on analytics

---

src/app/components/gv-analytics-filters/gv-analytics-filters.component.html
src/app/components/gv-analytics-filters/gv-analytics-filters.component.ts
src/app/pages/application/application-analytics/application-analytics.component.html
src/app/pages/application/application-analytics/application-analytics.component.ts
src/app/pages/application/application-logs/application-logs.component.html
src/app/pages/application/application-logs/application-logs.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

fix: Add a navigation button / link between analytics and logs

---

src/app/pages/application/application-members/application-members.component.html
src/app/pages/application/application-members/application-members.component.ts
src/app/services/notification.service.ts
src/styles.scss

fix(portal): improve application members management

---

src/app/components/gv-contact/gv-contact.component.ts
src/app/test/user-testing-module.ts

fix: display email error msg in good case

---

src/app/app-routing.module.ts
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.html
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts
src/app/services/nav-route.service.ts

fix: hide select box if empty categories

---

src/app/pages/application/application-logs/application-logs.component.html

fix: The label 'on' is too much on the log's detail

---

src/app/app-routing.module.ts
src/app/components/gv-header-item/gv-header-item.component.ts
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.html
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts
src/app/pages/user/user-notification/user-notification.component.spec.ts
src/app/resolvers/category.resolver.ts
src/app/services/event.service.spec.ts

fix: Avoid to load category (XHR) twice

---

src/app/services/nav-route.service.ts

fix: The menu item application's subscription is not correctly active

---

src/app/app.component.html

fix: use rounded image in user-menu

---

src/app/components/gv-documentation/gv-documentation.component.css
src/app/components/gv-documentation/gv-documentation.component.html
src/app/components/gv-documentation/gv-documentation.component.ts

fix(documentation): resolve gv-tree position

---

src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

fix(portal): change gv-metrics description to add precision

---

src/app/app.component.html
src/app/app.component.ts

fix: remove the ghost of homepage

---

src/app/app.component.ts
src/app/components/gv-analytics-filters/gv-analytics-filters.component.ts
src/app/pages/application/application-logs/application-logs.component.html
src/app/pages/application/application-logs/application-logs.component.ts
src/app/services/analytics.service.ts
src/app/services/scroll.service.spec.ts
src/app/services/scroll.service.ts

fix: resolve scroll on log selection

---

src/app/components/gv-analytics-dashboard/gv-analytics-dashboard.component.ts
src/app/components/gv-analytics-filters/gv-analytics-filters.component.ts
src/app/pages/application/application-analytics/application-analytics.component.html

refactor: synchronise analytics filters with queryParams

---

src/app/app-routing.module.ts
src/app/pages/registration/registration-confirmation/registration-confirmation.component.html

fix(portal): change registration and resetPassword route configuration

---

src/app/pages/application/application-general/application-general.component.css
src/app/pages/application/application-general/application-general.component.html
src/app/pages/application/application-general/application-general.component.ts
src/app/services/auth.service.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

fix: Unable to renew client secret

---

src/app/pages/application/application-logs/application-logs.component.ts

fix: JSON log body is not well colored

---

src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

fix(portal): add parameters for plural in translation

---

src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts

fix(portal): fix metrics variable name

---

README.adoc
package.json

Closes gravitee-io/issues#3624

feat(chore): replace 'start' by 'serve'

---

src/app/app.component.ts
src/app/pages/application/application-subscriptions/application-subscriptions.component.css
src/app/pages/application/application-subscriptions/application-subscriptions.component.html
src/app/pages/application/application-subscriptions/application-subscriptions.component.ts
src/app/pages/applications/applications-routing.module.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

fix: manage my api-keys

---

src/app/directives/gv-slot.ts

fix(menu): resolve slots injection

---

src/app/app.component.css

fix: resolve homepage title form small resolution 

---

src/app/components/gv-documentation/gv-documentation.component.ts

fix: resolve infinite loading of empty documentation

---

package.json
src/app/app.component.ts
src/app/model/itemResourceType.enum.ts
src/app/pages/api/api-general/api-general.component.html
src/app/pages/api/api-general/api-general.component.ts
src/app/pages/api/api-subscribe/api-subscribe.component.html
src/app/pages/api/api-subscribe/api-subscribe.component.ts
src/app/pages/application/application-general/application-general.component.html
src/app/pages/application/application-general/application-general.component.ts
src/app/pages/application/application-members/application-members.component.html
src/app/pages/application/application-members/application-members.component.ts
src/app/pages/application/application-subscriptions/application-subscriptions.component.html
src/app/pages/application/application-subscriptions/application-subscriptions.component.ts

fix(portal): gv-list are now clickable to navigate to apis and apps

---

src/app/components/gv-analytics-filters/gv-analytics-filters.component.html
src/app/components/gv-analytics-filters/gv-analytics-filters.component.ts
src/app/directives/gv-form-control.directive.ts
src/app/pages/api/api-subscribe/api-subscribe.component.html
src/app/pages/application/application-creation/application-creation.component.ts
src/app/pages/registration/registration-confirmation/registration-confirmation.component.ts
src/app/pages/reset-password/reset-password-confirmation/reset-password-confirmation.component.ts
src/app/pages/user/user-notification/user-notification.component.css
src/app/pages/user/user-notification/user-notification.component.html
src/app/utils/gv-validators.ts
src/styles.scss

fix: add validators on analytics/logs form

---

package-lock.json
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/i18n-components.ts

fix: Display to consumer entrypoints of the API

---

src/app/pages/application/application-members/application-members.component.css

fix: add missing css classes

---

src/app/pages/subscriptions/subscriptions.component.html
src/app/pages/subscriptions/subscriptions.component.ts
src/assets/i18n/fr.json

fix: Empty message incorrect on subscriptions screen

---

src/app/pages/subscriptions/subscriptions.component.css
src/app/pages/subscriptions/subscriptions.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

fix: Problem on columns width on subscriptions screen

---

src/app/pages/api/api-subscribe/api-subscribe.component.html
src/app/pages/application/application-logs/application-logs.component.html
src/app/pages/application/application-subscriptions/application-subscriptions.component.css
src/app/pages/application/application-subscriptions/application-subscriptions.component.html
src/app/pages/application/application-subscriptions/application-subscriptions.component.ts
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.html
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts
src/app/pages/subscriptions/subscriptions.component.css
src/app/pages/subscriptions/subscriptions.component.html
src/app/pages/subscriptions/subscriptions.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/css/form.css
src/styles.scss

Fixes gravitee-io/issues#3611
Fixes gravitee-io/issues#3486
Fixes gravitee-io/issues#3452

fix(portal): change cursor to pointer in subscriptions list

---

src/app/components/gv-documentation/gv-documentation.component.css
src/app/components/gv-documentation/gv-documentation.component.ts
src/app/components/gv-page-markdown/gv-page-markdown.component.css
src/app/components/gv-page-redoc/gv-page-redoc.component.ts

fix: resolve documentation display with scrollbar

---

package-lock.json
src/app/pages/dashboard/dashboard.component.css
src/app/pages/dashboard/dashboard.component.html
src/app/pages/dashboard/dashboard.component.spec.ts
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/user/user-notification/user-notification.component.html
src/app/services/analytics.service.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/styles.scss

feat: User dashboard

---

src/app/pages/application/application-general/application-general.component.css
src/app/pages/application/application-general/application-general.component.html
src/app/pages/application/application-general/application-general.component.ts
src/app/pages/dashboard/dashboard.component.html
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/css/form.css
src/i18n-server-errors.ts
src/styles.scss

fix: show readonly application info for simple user

---

src/app/app-routing.module.ts
src/app/pages/api/api-general/api-general.component.ts
src/app/pages/application/application-general/application-general.component.ts
src/app/pages/application/application-members/application-members.component.ts
src/app/pages/application/application-subscriptions/application-subscriptions.component.ts
src/app/pages/applications/applications-routing.module.ts
src/app/pages/applications/applications.module.ts
src/app/resolvers/permissions-resolver.service.ts
src/app/services/auth-guard.service.ts
src/app/services/nav-route.service.spec.ts
src/app/services/nav-route.service.ts
src/app/services/permission-guard.service.spec.ts
src/app/services/permission-guard.service.ts

fix: Check permissions on app notifications

---

package-lock.json
src/app/components/gv-analytics-filters/gv-analytics-filters.component.html
src/app/components/gv-analytics-filters/gv-analytics-filters.component.ts
src/app/interceptors/api-request.interceptor.ts
src/app/pages/application/application-logs/application-logs.component.html
src/app/pages/application/application-logs/application-logs.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

feat: Allows to export logs

---

src/app/pages/application/application-members/application-members.component.ts

fix(portal): fix promise.resolve

---

src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/i18n-server-errors.ts

fix(portal): translate '403' errors from API

---

package-lock.json
src/app/pages/login/login.component.ts
src/app/services/auth.service.ts

fix: Unable to authenticate using oidc / am auth provider

---

src/app/app.component.ts

fix(portal): short displayName computed in UI instead of in API

---

src/app/pages/single-page/single-page.component.css
src/app/pages/single-page/single-page.component.ts

fix: Unnecessary margin on portal homepage

---

src/app/pages/user/user-account/user-account.component.ts

fix: Error while saving my user profile

---

angular.json

chore: Generate dist on the root

---

src/app/app-routing.module.ts
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.html
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

fix: Add a catalog's menu item to display all the APIs

---

src/app/app.component.html

fix: Do not display footer if empty

---

src/app/interceptors/api-request.interceptor.ts

fix: We should not display error on background http calls

---

src/app/app-routing.module.ts
src/app/app.component.html
src/app/app.component.ts
src/app/model/feature.enum.ts
src/app/services/configuration.service.ts
src/app/services/nav-route.service.ts

fix: Force authentication to access portal if checked

---

src/app/services/subscribe-guard.service.ts

fix: Not redirected after authentication

---

package-lock.json
package.json
src/app/directives/gv-form-control.directive.ts
src/app/pages/api/api-subscribe/api-subscribe.component.css
src/app/pages/application/application-creation/application-creation-step1/application-creation-step1.component.html
src/app/pages/application/application-creation/application-creation-step1/application-creation-step1.component.spec.ts
src/app/pages/application/application-creation/application-creation-step1/application-creation-step1.component.ts
src/app/pages/application/application-creation/application-creation-step2/application-creation-step2.component.html
src/app/pages/application/application-creation/application-creation-step2/application-creation-step2.component.spec.ts
src/app/pages/application/application-creation/application-creation-step2/application-creation-step2.component.ts
src/app/pages/application/application-creation/application-creation-step3/application-creation-step3.component.html
src/app/pages/application/application-creation/application-creation-step3/application-creation-step3.component.spec.ts
src/app/pages/application/application-creation/application-creation-step3/application-creation-step3.component.ts
src/app/pages/application/application-creation/application-creation-step4/application-creation-step4.component.html
src/app/pages/application/application-creation/application-creation-step4/application-creation-step4.component.spec.ts
src/app/pages/application/application-creation/application-creation-step4/application-creation-step4.component.ts
src/app/pages/application/application-creation/application-creation.component.css
src/app/pages/application/application-creation/application-creation.component.html
src/app/pages/application/application-creation/application-creation.component.ts
src/app/pages/application/application-general/application-general.component.css
src/app/pages/application/application-general/application-general.component.html
src/app/pages/application/application-general/application-general.component.ts
src/app/pages/applications/applications-routing.module.ts
src/app/pages/applications/applications.module.ts
src/app/resolvers/application-type.resolver.ts
src/app/resolvers/enabled-application-types.resolver.ts
src/css/form.css
src/css/layout.css
src/styles.scss

feat(portal): manage application's grant flow

---

src/styles.scss

fix: decrease the min-height of page content

---

src/app/pages/registration/registration-confirmation/registration-confirmation.component.html
src/app/pages/registration/registration-confirmation/registration-confirmation.component.ts
src/app/pages/registration/registration.component.html
src/app/pages/registration/registration.component.ts
src/app/pages/reset-password/reset-password-confirmation/reset-password-confirmation.component.html
src/app/pages/reset-password/reset-password-confirmation/reset-password-confirmation.component.ts
src/app/pages/reset-password/reset-password.component.html
src/app/pages/reset-password/reset-password.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/css/form.css

fix(portal): use prettier message

---

package-lock.json
src/app/components/gv-documentation/gv-documentation.component.ts
src/app/components/gv-page-redoc/gv-page-redoc.component.ts

fix: resolve display of redoc page in single page mode

---

src/app/app.component.ts

fix: resolve condition to catch homepage

---

src/app/app.component.ts

fix: resolve display of homepage when resize window

---

src/app/app.component.css
src/app/components/gv-documentation/gv-documentation.component.css
src/app/components/gv-documentation/gv-documentation.component.ts
src/app/components/gv-page-markdown/gv-page-markdown.component.ts
src/app/services/scroll.service.ts

fix: resolve documentation with long header

---

src/app/app.component.css
src/app/app.component.html

fix: use layer for hide homepage image with sticky menu

---

src/app/pages/api/api-subscribe/api-subscribe.component.ts
src/app/pages/application/application-creation/application-creation-step1/application-creation-step1.component.ts
src/app/pages/application/application-creation/application-creation-step2/application-creation-step2.component.ts
src/app/pages/application/application-creation/application-creation-step3/application-creation-step3.component.ts
src/app/pages/application/application-creation/application-creation-step4/application-creation-step4.component.ts
src/app/pages/application/application-creation/application-creation.component.css
src/app/pages/application/application-creation/application-creation.component.ts

feat: improve validation steps in application creation

---

src/app/app-routing.module.ts

fix(portal): add single category page for view Links

---

src/app/pages/applications/applications.component.css
src/app/pages/applications/applications.component.html
src/app/pages/applications/applications.component.ts

refactor: use gv-card-list in applications

---

src/app/pages/homepage/homepage.component.html
src/styles.scss

feat: improve homepage title

---

package.json
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts

Closes gravitee-io/issues#3767

feat(management): update portal SDK version

---

src/app/app.component.html

fix(portal): hide only configurable links

---

src/app/components/gv-analytics-filters/gv-analytics-filters.component.css

fix(logs): align advanced filters in low resolution

---

angular.json
src/app/components/gv-page-markdown/gv-page-markdown.component.ts

fix(portal): add code highlight when rendering markdown

---

src/app/services/analytics.service.ts

fix: Errors when selecting a filter on an empty user agent

---

package-lock.json
src/app/pages/homepage/homepage.component.css
src/app/pages/homepage/homepage.component.html
src/app/pages/homepage/homepage.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

fix: Top APIs

---

src/app/pages/applications/applications.component.ts
src/app/pages/dashboard/dashboard.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

feat(applications): add link to subscriptions

---

src/app/app-routing.module.ts
src/app/app.component.html
src/app/app.component.ts
src/app/components/gv-analytics-filters/gv-analytics-filters.component.html
src/app/components/gv-contact/gv-contact.component.html
src/app/components/gv-cookie-consent/gv-cookie-consent.component.html
src/app/pages/api/api-general/api-general.component.html
src/app/pages/api/api-subscribe/api-subscribe.component.html
src/app/pages/application/application-creation/application-creation-step3/application-creation-step3.component.html
src/app/pages/application/application-creation/application-creation.component.html
src/app/pages/application/application-general/application-general.component.html
src/app/pages/application/application-members/application-members.component.html
src/app/pages/application/application-subscriptions/application-subscriptions.component.html
src/app/pages/login/login.component.html
src/app/pages/not-found/not-found.component.html
src/app/pages/user/user-account/user-account.component.html
src/app/services/nav-route.service.ts

fix: improve category handling

---

src/app/components/gv-documentation/gv-documentation.component.css
src/app/components/gv-markdown-toc/gv-markdown-toc.component.css
src/app/components/gv-page-markdown/gv-page-markdown.component.css
src/app/components/gv-page-markdown/gv-page-markdown.component.html
src/app/pages/dashboard/dashboard.component.css
src/app/pages/dashboard/dashboard.component.html
src/app/pages/homepage/homepage.component.css
src/app/services/scroll.service.ts
src/styles.scss

fix: display large documentation

---

src/app/components/gv-analytics-filters/gv-analytics-filters.component.html
src/css/form.css

fix: make filter elements more visible

---

src/app/app.module.ts
src/app/interceptors/api-request.interceptor.ts
src/app/pages/login/login.component.ts
src/app/pages/registration/registration-confirmation/registration-confirmation.component.ts
src/app/pages/registration/registration.component.ts
src/app/pages/reset-password/reset-password-confirmation/reset-password-confirmation.component.ts
src/app/pages/reset-password/reset-password.component.ts
src/app/services/recaptcha.service.spec.ts
src/app/services/recaptcha.service.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

Closes gravitee-io/issues#3668

feat(security): add recaptcha and csrf support on portal

---

src/app/components/gv-page-markdown/gv-page-markdown.component.css
src/app/components/gv-page-markdown/gv-page-markdown.component.html
src/app/pages/homepage/homepage.component.css
src/app/pages/homepage/homepage.component.html

fix(documentation): add var css to manage margin

---

src/app/components/gv-markdown-toc/gv-markdown-toc.component.ts

fix(portal): change the way the toc in computed

---

src/app/app-routing.module.ts
src/app/components/gv-documentation/gv-documentation.component.ts
src/app/components/gv-page-redoc/gv-page-redoc.component.ts
src/app/components/gv-page/gv-page.component.ts
src/app/pages/api/api-general/api-general.component.css
src/app/pages/api/api-general/api-general.component.html
src/app/pages/api/api-general/api-general.component.spec.ts
src/app/pages/api/api-general/api-general.component.ts
src/app/pages/homepage/homepage.component.html
src/app/resolvers/api-homepage.resolver.ts
src/app/services/scroll.service.ts

fix(documentation): improve redoc integration in api/homepage

---

src/app/model/feature.enum.ts
src/app/pages/api/api-general/api-general.component.html
src/app/pages/api/api-general/api-general.component.ts

fix: resolve the rating feature

---

src/app/app.component.ts
src/app/components/gv-documentation/gv-documentation.component.ts
src/app/components/gv-markdown-toc/gv-markdown-toc.component.css
src/app/components/gv-markdown-toc/gv-markdown-toc.component.ts
src/app/components/gv-page-markdown/gv-page-markdown.component.css
src/app/components/gv-page-markdown/gv-page-markdown.component.ts
src/app/components/gv-page-redoc/gv-page-redoc.component.ts

fix: resolve documentation display

---

angular.json
src/app/components/gv-page-swaggerui/gv-page-swaggerui.component.ts

fix(portal): use default oauth2-redirect.html

---

src/app/app.component.ts
src/app/pages/api/api-general/api-general.component.html
src/app/pages/api/api-general/api-general.component.ts

fix(portal): replace <a> with gv-button

---

package.json
src/app/app-routing.module.ts
src/app/pages/api/api-general/api-general.component.html
src/app/pages/api/api-general/api-general.component.ts
src/app/resolvers/api-informations.resolver.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/i18n-dynamic-values.ts

fix(api): resolve display of configurable informations

---

package.json
src/app/pages/login/login.component.css
src/app/pages/login/login.component.html
src/app/pages/login/login.component.ts

fix(portal): allow customization of oidc and gravitee auth button

---

src/app/app.component.html
src/app/app.component.ts

fix: When forceLogin is enabled, we cannot register anymore

---

src/app/pages/subscriptions/subscriptions.component.html
src/app/pages/subscriptions/subscriptions.component.ts

fix(portal): force skeleton mode while apis have not been loaded

---

src/app/components/gv-analytics-filters/gv-analytics-filters.component.html
src/app/pages/api/api-general/api-general.component.html
src/app/pages/api/api-subscribe/api-subscribe.component.html
src/app/pages/application/application-creation/application-creation-step2/application-creation-step2.component.html
src/app/pages/application/application-general/application-general.component.html
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.html
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/subscriptions/subscriptions.component.ts

Closes gravitee-io/issues#3842

feat(portal): enable tags on gv-promote & gv-card-full to be clicked

---

src/app/pages/api/api-subscribe/api-subscribe.component.ts
src/app/pages/application/application-creation/application-creation-step4/application-creation-step4.component.html
src/app/pages/application/application-creation/application-creation.component.ts

fix: resolve display of error msg in app creation & api subscription

---

package-lock.json
package.json
src/app/pages/api/api-subscribe/api-subscribe.component.html
src/app/pages/api/api-subscribe/api-subscribe.component.ts
src/app/pages/application/application-logs/application-logs.component.html
src/app/pages/subscriptions/subscriptions.component.html
src/app/pages/subscriptions/subscriptions.component.ts

refactor: upgrade gv-code api

---

package.json
src/app/app-routing.module.ts
src/app/app.component.ts
src/app/model/feature.enum.ts
src/app/pages/api/api-general/api-general.component.html
src/app/pages/api/api-general/api-general.component.ts
src/app/pages/api/api-subscribe/api-subscribe.component.html
src/app/pages/api/api-subscribe/api-subscribe.component.ts
src/app/pages/catalog/categories/categories.component.ts
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.html
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts
src/app/pages/homepage/homepage.component.ts
src/app/resolvers/category.resolver.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

fix(): rename view in category

---

src/app/pages/api/api-general/api-general.component.css
src/app/pages/api/api-general/api-general.component.html
src/app/pages/api/api-subscribe/api-subscribe.component.css
src/app/pages/api/api-subscribe/api-subscribe.component.html
src/app/pages/api/api-subscribe/api-subscribe.component.ts

fix(portal): some CSS to format URLs

---

src/app/app.module.ts
src/app/shared/shared.module.ts

fix: Load i18n files according to relative path

---

src/app/app.component.css
src/app/app.component.html

fix(portal): use a grid to place elements in footer

---

package.json
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts

fix(portal): new query param to select or not promoted apis

---

docker/config/templates/config.json.tmpl
package.json
pom.xml
src/app/app.module.ts
src/app/services/auth.service.ts
src/app/services/configuration.service.ts
src/app/services/current-user.service.ts
src/assets/config.json

Fixes gravitee-io/issues#4005
Fixes gravitee-io/issues#3968

fix(portal): capitalize parameter + override default baseURL in dist

---

src/app/pages/subscriptions/subscriptions.component.ts

fix: Cannot list my subscriptions in some cases

---

src/app/components/gv-header-item/gv-header-item.component.ts
src/app/pages/application/application-general/application-general.component.html
src/app/pages/application/application-general/application-general.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

feat: Allows to define a background on the APIs/Apps/Categories headers

---

src/app/pages/application/application-creation/application-creation.component.css

fix(portal): modify object-fit of the image

---

src/app/pages/application/application-creation/application-creation-step4/application-creation-step4.component.ts

fix(portal): fix array indices

---

src/app/app.module.ts
src/app/directives/gv-checkbox-control-value-accessor.directive.ts
src/app/shared/shared.module.ts

fix: bind copy to sender in user contact form

---

src/app/components/gv-page-markdown/gv-page-markdown.component.css

fix(markdown): add custom css for table

---

src/app/pages/api/api-subscribe/api-subscribe.component.html
src/app/pages/api/api-subscribe/api-subscribe.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

fix(subscription): handle OAuth 2.0 and JWT Plans subscription success step

---

src/app/services/auth.service.ts

fix(portal): remove provider id from localstorage after effective logout

---

src/app/services/auth.service.ts

fix: Unable to logout when using AM IDP

---

src/app/components/gv-documentation/gv-documentation.component.ts
src/app/components/gv-page-markdown/gv-page-markdown.component.ts
src/app/pages/single-page/single-page.component.ts

Closes gravitee-io/issues#4072

feat(management): add link to internal page in documentation

---

src/app/pages/application/application-creation/application-creation-step3/application-creation-step3.component.ts
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.css
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.html
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

Closes gravitee-io/issues#4067

feat(management): associate a page to a category

---

src/app/components/gv-page-markdown/gv-page-markdown.component.ts

fix gravitee-io/issues#4149
fix gravitee-io/issues#3156

fix(management): resolve API import/export

---

src/app/app.module.ts
src/app/shared/shared.module.ts

Closes gravitee-io/issues#4266

feat(portal): fix import in module definition

---

src/app/components/gv-documentation/gv-documentation.component.ts

Closes gravitee-io/issues#4267

feat(portal): find the right item in the menu

---

src/app/pages/api/api-general/api-general.component.ts
src/app/pages/homepage/homepage.component.ts

fix(portal): ad event listener on homepage component for internal link

---

src/app/components/gv-page-markdown/gv-page-markdown.component.css
src/app/components/gv-page-markdown/gv-page-markdown.component.html
src/app/components/gv-page-markdown/gv-page-markdown.component.ts
src/app/components/gv-select-dashboard/gv-select-dashboard.component.ts
src/app/pages/application/application-general/application-general.component.ts

Closes gravitee-io/issues#4066

feat(management): associate assets to pages

---

pom.xml

chore(portal): change build phase for replacer plugin

---

src/app/pages/application/application-logs/application-logs.component.css
src/app/pages/application/application-logs/application-logs.component.html

fix(portal): do not apply overflow on title

---

package.json

fix(portal): use last version of ui-components

---

projects/portal-webclient-sdk/src/lib/model/userInput.ts
src/app/pages/user/user-account/user-account.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/i18n-components.ts

Closes gravitee-io/issues#4316

feat(pictures): avatar is no longer mandatory in user update

---

src/assets/i18n/en.json

Fixes https://github.com/gravitee-io/issues/issues/4379

Very small typo fix - advise/advice 

---

src/assets/i18n/en.json

Closes gravitee-io/issues#4383

fix(typo): fix typo in en translation

---

scripts/update-sdk.sh

chore(): improve update-sdk.sh script to avoid manual update

---

src/app/components/gv-page-markdown/gv-page-markdown.component.css

fix(portal): display inline code on single line

---

src/assets/i18n/fr.json

Fixes https://github.com/gravitee-io/issues/issues/4504

Fix typo in FR

---

src/app/components/gv-page-markdown/gv-page-markdown.component.css
src/app/components/gv-page-markdown/gv-page-markdown.component.spec.ts
src/app/components/gv-page-markdown/gv-page-markdown.component.ts
src/app/services/scroll.service.spec.ts
src/app/services/scroll.service.ts

fix(portal): fix anchor links inside markdown

---

src/app/components/gv-documentation/gv-documentation.component.spec.ts
src/app/components/gv-documentation/gv-documentation.component.ts

fix: add link to internal page in documentation

---

angular.json
build.json
pom.xml

Closes gravitee-io/issues#4459

feat(portal): serve portal version in build.json

---

package.json

fix(portal): update ui-components version to fix gv-tag width issue

---

src/app/components/gv-analytics-dashboard/gv-analytics-dashboard.component.ts
src/app/pages/application/application-metadata/application-metadata.component.ts
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/subscriptions/subscriptions.component.ts

fix(portal): render the icon once in subscriptions table

---

src/app/components/gv-page-redoc/gv-page-redoc.component.ts

Closes gravitee-io/issues#4585

fix(management): Redoc is not working with a private API on dist

---

src/app/components/gv-page-markdown/gv-page-markdown.component.spec.ts
src/app/components/gv-page-markdown/gv-page-markdown.component.ts

* refactor marked `renderer`
* add unit tests
Fixes gravitee-io/issues#4620

fix(portal): fix portal image URL

---

package-lock.json
package.json
scripts/serve.js

chore: add proxy middleware for testing app in production mode

---

package-lock.json
src/app/components/gv-search-api/gv-search-api.component.ts

fix(portal): add api labels on search api component

---

package-lock.json
src/app/pages/application/application-logs/application-logs.component.ts

fix(portal): resolve logs pagination

---

build.json
src/app/pages/subscriptions/subscriptions.component.ts

fix: Example cURL not displayed for an unpublished API on subscriptions

---

build.json
src/app/components/gv-page-markdown/gv-page-markdown.component.spec.ts
src/app/components/gv-page-markdown/gv-page-markdown.component.ts

fix: Backport 4620

---

build.json
src/app/pages/api/api-subscribe/api-subscribe.component.css
src/app/pages/api/api-subscribe/api-subscribe.component.html
src/app/pages/api/api-subscribe/api-subscribe.component.ts
src/app/pages/application/application-creation/application-creation-step3/application-creation-step3.component.html
src/app/pages/application/application-creation/application-creation-step4/application-creation-step4.component.html
src/app/pages/application/application-creation/application-creation-step4/application-creation-step4.component.ts
src/app/pages/application/application-creation/application-creation.component.css
src/app/pages/application/application-creation/application-creation.component.html
src/app/pages/application/application-creation/application-creation.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json
src/i18n-server-errors.ts

fix(portal): check the version of GCU

---

src/app/components/gv-page-markdown/gv-page-markdown.component.spec.ts
src/app/components/gv-page-markdown/gv-page-markdown.component.ts

fix(portal): use baseURL in media link

---

projects/portal-webclient-sdk/src/lib/model/user.ts
projects/portal-webclient-sdk/src/lib/model/userInput.ts
src/app/pages/user/user-account/user-account.component.html
src/app/pages/user/user-account/user-account.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

feat(management): edit my account information

---

src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts

fix(portal): reset filter when "all APIs" selected

---

projects/portal-webclient-sdk/src/lib/model/filterApiQuery.ts
src/app/app-routing.module.ts
src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts

Fixes https://github.com/gravitee-io/issues/issues/4826

fix: backport 4825

---

src/app/pages/catalog/filtered-catalog/filtered-catalog.component.ts

Fixes https://github.com/gravitee-io/issues/issues/4824

fix: backport 4823

---

src/app/components/gv-page-markdown/gv-page-markdown.component.spec.ts
src/app/components/gv-page-markdown/gv-page-markdown.component.ts

Fixes https://github.com/gravitee-io/issues/issues/4670

fix: backport 4669 to 3.0.x

---

src/app/pages/subscriptions/subscriptions.component.ts

Fixes https://github.com/gravitee-io/issues/issues/4681

fix: backport 4680

---

src/app/pages/user/user-account/user-account.component.ts

style(): fix lint errors

---

src/app/pages/applications/applications.component.ts

Fixes https://github.com/gravitee-io/issues/issues/4677

fix: do not display error when metrics cannot be retrieved

---

src/app/pages/application/application-general/application-general.component.html

fix(portal): display clientId for simple application

---

src/assets/i18n/en.json

'Note' seems to be from the French original 'Noter'.
Issue: https://github.com/gravitee-io/issues/issues/4857

This should be 'Rate' in English

---

src/app/components/gv-analytics-dashboard/gv-analytics-dashboard.component.ts

Fixes https://github.com/gravitee-io/issues/issues/4747

feat: console dashboard page

---

src/app/pages/application/application-subscriptions/application-subscriptions.component.html
src/app/pipes/localized-date.pipe.ts

fix(portal): remove invalid date label for pending subscription

---

src/app/pages/application/application-general/application-general.component.css

Closes gravitee-io/issues#4926

fix: Align delete link in aside box

---

src/app/services/auth.service.ts

fix(portal): resolve logout from external IDP

---

src/app/pages/api/api-subscribe/api-subscribe.component.ts
src/app/pages/application/application-creation/application-creation-step3/application-creation-step3.component.ts
src/app/pages/application/application-subscriptions/application-subscriptions.component.ts
src/css/form.css

Closes gravitee-io/issues#5076

chore: Backport #4653

---

src/app/components/gv-page-swaggerui/gv-page-swaggerui.component.ts

fix(portal): remove authorize button if "try it" mode is disabled

---

angular.json
package-lock.json
package.json

fix: upgrade ui-components to use latest version of gv-table and gv-code

---

angular.json
build.json
package-lock.json
package.json

fix(portal): use the latest version of gv-code

---

build.json
package-lock.json
pom.xml
src/app/pages/applications/applications-routing.module.ts

Closes gravitee-io/issues#5207

fix: application menus are not correctly displayed

---

package.json

chore(): update ui-component dependency to solve css rendering issue

---

package-lock.json
package.json

fix gravitee-io/issues#5234
fix gravitee-io/issues#5233

chore: upgrade ui-components to 2.0.0

---

build.json
src/app/app.component.html
src/app/app.component.ts

Closes gravitee-io/issues#4856

feat: Override the main sentence in the homepage

---

package-lock.json
package.json

Fixes https://github.com/gravitee-io/issues/issues/5383

chore: update ui-components to 2.3.1

---

package-lock.json
package.json
projects/portal-webclient-sdk/src/lib/model/themeLinks.ts

Issue/5389 upgrade UI components

---

src/app/pages/application/application-metadata/application-metadata.component.ts

fix(portal): use innerText for render metadata name

---

src/app/pages/application/application-creation/application-creation-step3/application-creation-step3.component.ts

fix: avoid method call on undefine subscribeList

---

src/assets/i18n/en.json

typo: 'information' is always singular

---

package-lock.json
package.json
src/app/components/gv-page-redoc/gv-page-redoc.component.ts

Closes gravitee-io/issues#5597

fix(redoc): footer overlap when using redoc viewer in api homepage

---

src/app/pages/application/application-subscriptions/application-subscriptions.component.html
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

**Issue**
https://github.com/gravitee-io/issues/issues/3887
**Description**
Display subscription end date
**Screenshot**

feat: display subscription end date

---

src/app/services/auth.service.ts

fix: allow utf8 character in the password

---

src/assets/i18n/fr.json

To fix some minor french grammar errors I detected during my tests

chore(grammar): minor french grammar fixes in i18n file

---

src/app/pages/login/login.component.html
src/app/pages/login/login.component.ts

fix(portal): apply custom color on provider authentication button

---

scripts/update-sdk.sh

update openapi filepath in update-sdk script, to fit monorepository architecture

chore: update openapi filepath in update-sdk script, to fit monorepository architecture

---

docker/Dockerfile

Closes gravitee-io/issues#6139

fix: Upgrade Nginx base image and upgrade libgcrypt

---

src/app/components/gv-search-api/gv-search-api.component.ts
src/app/pages/catalog/search/catalog-search.component.html
src/app/pages/catalog/search/catalog-search.component.ts
src/assets/i18n/cs.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

2839 portal advanced search
